In [156]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score,r2_score,classification_report,confusion_matrix,mean_squared_error
from sklearn.preprocessing import StandardScaler,OneHotEncoder,LabelEncoder,PolynomialFeatures
from sklearn.tree import DecisionTreeClassifier
from sklearn.inspection import DecisionBoundaryDisplay
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer,make_column_selector
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE

In [3]:
data = pd.read_csv("adult.csv")
data.head()

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   age              48842 non-null  int64
 1   workclass        48842 non-null  object
 2   fnlwgt           48842 non-null  int64
 3   education        48842 non-null  object
 4   educational-num  48842 non-null  int64
 5   marital-status   48842 non-null  object
 6   occupation       48842 non-null  object
 7   relationship     48842 non-null  object
 8   race             48842 non-null  object
 9   gender           48842 non-null  object
 10  capital-gain     48842 non-null  int64
 11  capital-loss     48842 non-null  int64
 12  hours-per-week   48842 non-null  int64
 13  native-country   48842 non-null  object
 14  income           48842 non-null  object
dtypes: int64(6), object(9)
memory usage: 5.6+ MB

In [5]:
data.workclass.unique()

array(['Private', 'Local-gov', '?', 'Self-emp-not-inc', 'Federal-gov',
       'State-gov', 'Self-emp-inc', 'Without-pay', 'Never-worked'],
      dtype=object)

In [6]:
Most_repeated_Value = data.workclass.mode()[0]

In [7]:
data.workclass = data.workclass.str.replace("?",Most_repeated_Value)

In [8]:
data.education.unique()

array(['11th', 'HS-grad', 'Assoc-acdm', 'Some-college', '10th',
       'Prof-school', '7th-8th', 'Bachelors', 'Masters', 'Doctorate',
       '5th-6th', 'Assoc-voc', '9th', '12th', '1st-4th', 'Preschool'],
      dtype=object)

In [9]:
data.education = data.education.str.strip().str.replace('-',' ')

In [10]:
education_change = str(np.random.choice(['7th','8th','1st','4th','5th','6th']))

In [11]:
data.education = data.education.replace(['7th-8th','5th-6th','1st-4th','-'],[education_change,education_change,education_change,' '])

In [12]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   age              48842 non-null  int64
 1   workclass        48842 non-null  object
 2   fnlwgt           48842 non-null  int64
 3   education        48842 non-null  object
 4   educational-num  48842 non-null  int64
 5   marital-status   48842 non-null  object
 6   occupation       48842 non-null  object
 7   relationship     48842 non-null  object
 8   race             48842 non-null  object
 9   gender           48842 non-null  object
 10  capital-gain     48842 non-null  int64
 11  capital-loss     48842 non-null  int64
 12  hours-per-week   48842 non-null  int64
 13  native-country   48842 non-null  object
 14  income           48842 non-null  object
dtypes: int64(6), object(9)
memory usage: 5.6+ MB

In [13]:
data['marital-status'] = data['marital-status'].str.strip().str.replace('-',' ')

In [14]:
data.occupation.unique()

array(['Machine-op-inspct', 'Farming-fishing', 'Protective-serv', '?',
       'Other-service', 'Prof-specialty', 'Craft-repair', 'Adm-clerical',
       'Exec-managerial', 'Tech-support', 'Sales', 'Priv-house-serv',
       'Transport-moving', 'Handlers-cleaners', 'Armed-Forces'],
      dtype=object)

In [15]:
data.occupation = data.occupation.str.strip().str.replace('-',' ').str.replace("?",data.occupation.mode()[0])

In [16]:
data.occupation.mode()[0]

'Prof specialty'

In [17]:
data.relationship.unique()

array(['Own-child', 'Husband', 'Not-in-family', 'Unmarried', 'Wife',
       'Other-relative'], dtype=object)

In [18]:
data.relationship = data.relationship.str.strip().str.replace("-",' ')

In [20]:
data.race.unique()

array(['Black', 'White', 'Asian-Pac-Islander', 'Other',
       'Amer-Indian-Eskimo'], dtype=object)

In [40]:
data[(data.select_dtypes("object")).replace('-',' ',regex=True).columns] = (data.select_dtypes("object")).replace('-',' ',regex=True)

In [ ]:
data

In [84]:
for i in data.select_dtypes("object").columns:
    uni = data[i].unique()
    print(f'[------{i}-----] :: {uni}')

[------workclass-----] :: ['Private' 'Local gov' 'Self emp not inc' 'Federal gov' 'State gov'
 'Self emp inc' 'Without pay' 'Never worked']
[------education-----] :: ['11th' 'HS grad' 'Assoc acdm' 'Some college' '10th' 'Prof school'
 '7th 8th' 'Bachelors' 'Masters' 'Doctorate' '5th 6th' 'Assoc voc' '9th'
 '12th' '1st 4th' 'Preschool']
[------marital-status-----] :: ['Never married' 'Married civ spouse' 'Widowed' 'Divorced' 'Separated'
 'Married spouse absent' 'Married AF spouse']
[------occupation-----] :: ['Machine op inspct' 'Farming fishing' 'Protective serv' 'Prof specialty'
 'Other service' 'Craft repair' 'Adm clerical' 'Exec managerial'
 'Tech support' 'Sales' 'Priv house serv' 'Transport moving'
 'Handlers cleaners' 'Armed Forces']
[------relationship-----] :: ['Own child' 'Husband' 'Not in family' 'Unmarried' 'Wife' 'Other relative']
[------race-----] :: ['Black' 'White' 'Asian Pac Islander' 'Other' 'Amer Indian Eskimo']
[------gender-----] :: ['Male' 'Female']
[------native-country-----] :: ['United States' '?' 'Peru' 'Guatemala' 'Mexico' 'Dominican Republic'
 'Ireland' 'Germany' 'Philippines' 'Thailand' 'Haiti' 'El Salvador'
 'Puerto Rico' 'Vietnam' 'South' 'Columbia' 'Japan' 'India' 'Cambodia'
 'Poland' 'Laos' 'England' 'Cuba' 'Taiwan' 'Italy' 'Canada' 'Portugal'
 'China' 'Nicaragua' 'Honduras' 'Iran' 'Scotland' 'Jamaica' 'Ecuador'
 'Yugoslavia' 'Hungary' 'Hong' 'Greece' 'Trinadad&Tobago'
 'Outlying US(Guam USVI etc)' 'France' 'Holand Netherlands']
[------income-----] :: ['<=50K' '>50K']

In [92]:
data['native-country'] = data['native-country'].replace("?",data['native-country'].mode()[0])

In [94]:
data['native-country'].unique()

array(['United States', 'Peru', 'Guatemala', 'Mexico',
       'Dominican Republic', 'Ireland', 'Germany', 'Philippines',
       'Thailand', 'Haiti', 'El Salvador', 'Puerto Rico', 'Vietnam',
       'South', 'Columbia', 'Japan', 'India', 'Cambodia', 'Poland',
       'Laos', 'England', 'Cuba', 'Taiwan', 'Italy', 'Canada', 'Portugal',
       'China', 'Nicaragua', 'Honduras', 'Iran', 'Scotland', 'Jamaica',
       'Ecuador', 'Yugoslavia', 'Hungary', 'Hong', 'Greece',
       'Trinadad&Tobago', 'Outlying US(Guam USVI etc)', 'France',
       'Holand Netherlands'], dtype=object)

In [155]:
data['income'].value_counts()

income
<=50K    37155
>50K     11687
Name: count, dtype: int64

In [109]:
data.describe()

,age,fnlwgt,educational-num,capital-gain,capital-loss,hours-per-week
count,48842.000000,4.884200e+04,48842.000000,48842.000000,48842.000000,48842.000000
mean,38.643585,1.896641e+05,10.078089,1079.067626,87.502314,40.422382
std,13.710510,1.056040e+05,2.570973,7452.019058,403.004552,12.391444
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.175505e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.781445e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.376420e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.490400e+06,16.000000,99999.000000,4356.000000,99.000000

In [111]:
x = data.drop('income',axis=1)
y = data.income

In [115]:
X_train,X_test,y_train,y_test = train_test_split(x,y,test_size=0.20,random_state=100)

In [139]:
num_column = X_train.select_dtypes("number")
Obj_column = X_train.select_dtypes("object")

In [140]:
number_data = Pipeline(
    [
('scale',StandardScaler()),
        ('filling',SimpleImputer(strategy="median"))
    ]
)
object_data = Pipeline(
    [
        ("encode",OneHotEncoder(drop="first",sparse_output=False,handle_unknown="ignore")),
        ('filling',SimpleImputer(strategy="most_frequent"))
    ]
)

In [144]:
Preprocessing = ColumnTransformer(
    transformers=[
        ('num',number_data,make_column_selector(dtype_include=np.number)),
        ('Obj',object_data,make_column_selector(dtype_include="object"))
    ]
)

In [147]:
model_Pipeline = Pipeline(
    [
        ('Preprocessor',Preprocessing),
        ('model',DecisionTreeClassifier(random_state=100))
        
    ]
)

In [158]:
smote = SMOTE(sampling_strategy='minority', random_state=42)
Xsmote ,Ysmote = smote.fit_resample(X_train,y_train)

ValueError: could not convert string to float: 'Private'

In [148]:
model_Pipeline.fit(X_train,y_train)

Pipeline(steps=[('Preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('scale',
                                                                   StandardScaler()),
                                                                  ('filling',
                                                                   SimpleImputer(strategy='median'))]),
                                                  <sklearn.compose._column_transformer.make_column_selector object at 0x000002103A515460>),
                                                 ('Obj',
                                                  Pipeline(steps=[('encode',
                                                                   OneHotEncoder(drop='first',
                                                                                 handle_unknown='ignore',
                                                                                 sparse_output=False)),
                                                                  ('filling',
                                                                   SimpleImputer(strategy='most_frequent'))]),
                                                  <sklearn.compose._column_transformer.make_column_selector object at 0x000002104402F770>)])),
                ('model', DecisionTreeClassifier(random_state=100))])

In [149]:
y_pre_test = model_Pipeline.predict(X_test)

In [150]:
accuracy_score(y_test,y_pre_test)

0.8151294912478247

In [152]:
print(classification_report(y_test,y_pre_test))

              precision    recall  f1-score   support

       <=50K       0.88      0.87      0.88      7420
        >50K       0.61      0.63      0.62      2349

    accuracy                           0.82      9769
   macro avg       0.75      0.75      0.75      9769
weighted avg       0.82      0.82      0.82      9769

In [153]:
y_pre_test

array(['>50K', '<=50K', '<=50K', ..., '>50K', '<=50K', '<=50K'],
      shape=(9769,), dtype=object)

In [161]:
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OrdinalEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

from imblearn.over_sampling import SMOTENC

import pandas as pd
import numpy as np

# Load Data
data = pd.read_csv("adult.csv")

# Replace ?
data = data.replace(" ?", np.nan)

# Features & Target
X = data.drop("income", axis=1)
y = data["income"]

# Train Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# Column Names
cat_cols = X_train.select_dtypes(include="object").columns
num_cols = X_train.select_dtypes(include=np.number).columns

# Numerical Pipeline
num_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

# Categorical Pipeline
cat_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', OrdinalEncoder())
])

# Preprocessing
preprocessor = ColumnTransformer([
    
    ('num', num_pipeline, num_cols),

    ('cat', cat_pipeline, cat_cols)
])

# Transform Train Data
X_train_processed = preprocessor.fit_transform(X_train)

# Transform Test Data
X_test_processed = preprocessor.transform(X_test)

# Categorical indices after transformation
cat_indices = list(range(
    len(num_cols),
    len(num_cols) + len(cat_cols)
))

# SMOTENC
smote = SMOTENC(
    categorical_features=cat_indices,
    random_state=42
)

# Apply SMOTE
X_smote, y_smote = smote.fit_resample(
    X_train_processed,
    y_train
)

# Model
model = LogisticRegression(max_iter=1000)

# Train
model.fit(X_smote, y_smote)

# Prediction
y_pred = model.predict(X_test_processed)

# Result
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

       <=50K       0.91      0.77      0.84      7431
        >50K       0.51      0.75      0.61      2338

    accuracy                           0.77      9769
   macro avg       0.71      0.76      0.72      9769
weighted avg       0.81      0.77      0.78      9769